CREATE TABLE Authors (
    AuthorID INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL
);

CREATE TABLE Categories (
    CategoryID INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(50) NOT NULL
);

CREATE TABLE Books (
    BookID INT PRIMARY KEY IDENTITY(1,1),
    Title NVARCHAR(200) NOT NULL,
    AuthorID INT NOT NULL FOREIGN KEY REFERENCES Authors(AuthorID),
    CategoryID INT NOT NULL FOREIGN KEY REFERENCES Categories(CategoryID),
    ISBN NVARCHAR(20) UNIQUE,
    PublishDate DATE
);

CREATE TABLE Members (
    MemberID INT PRIMARY KEY IDENTITY(1,1),
    FullName NVARCHAR(100) NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Phone NVARCHAR(20),
    JoinDate DATE NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Loans (
    LoanID INT PRIMARY KEY IDENTITY(1,1),
    BookID INT NOT NULL FOREIGN KEY REFERENCES Books(BookID),
    MemberID INT NOT NULL FOREIGN KEY REFERENCES Members(MemberID),
    CheckoutDate DATE NOT NULL DEFAULT GETDATE(),
    DueDate DATE NOT NULL,
    ReturnDate DATE
);

CREATE TABLE Fines (
    FineID INT PRIMARY KEY IDENTITY(1,1),
    LoanID INT NOT NULL FOREIGN KEY REFERENCES Loans(LoanID),
    Amount DECIMAL(10,2) NOT NULL,
    Paid BIT NOT NULL DEFAULT 0
);